// ===== Product Data — Real Dropshipping from KSA Drop + M5AZN =====
// Real product images from Shopify CDN
// Prices: Wholesale cost → Retail price (3x+ margin)
// Currency: SAR

const CDN = 'https://cdn.shopify.com/s/files/1/0866/8699/0652/files/';

const PRODUCTS = [
  // ===== Health & Beauty =====
  { id: 1, name: "مبخرة إلكترونية مشط 2 في 1", category: "beauty", cost: 36, price: 129, oldPrice: 179, rating: 4.8, reviews: 234, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", icon: "🪔", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'haircomb1.jpg', imgs: [CDN+'haircomb1.jpg',CDN+'haircomb2.jpg',CDN+'haircomb3.jpg'], desc: "مبخرة إلكترونية ذكية — تحول المبخرة التقليدية لجهاز عصري. سلك تسخين كهربائي عالي الحرارة يوقد البخور بنفس درجة الفحم. يشمل غطاء مشط لتسريح الشعر بعبقة فاخرة.", specs: ["سلك تسخين كهربائي", "غطاء مشط مدمج", "شحن USB-C", "بطارية 1200 mAh"] },
  { id: 2, name: "جهاز إزالة الرؤوس السوداء 5 في 1", category: "beauty", cost: 45, price: 169, oldPrice: 219, rating: 4.7, reviews: 189, badge: "خصم", gradient: "linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)", icon: "✨", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'1_f7ac3278-1613-42e1-a2fe-10150e7b7c35.webp', imgs: [CDN+'1_f7ac3278-1613-42e1-a2fe-10150e7b7c35.webp'], desc: "جهاز شفط الرؤوس السوداء والحبوب — 5 رؤوس مختلفة للتنظيف العميق. تقنية شفط قوية لكن لطيفة على البشرة.", specs: ["5 رؤوس شفط", "شحن USB", "3 مستويات شدة", "للبشرة الدهنية والعادية"] },
  { id: 3, name: "قصافة أظافر أطفال كهربائية", category: "beauty", cost: 45, price: 159, oldPrice: null, rating: 4.8, reviews: 145, badge: "جديد", gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)", icon: "✂️", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'3_42afcbca-5a2e-452a-b152-e7a11bfba480.webp', imgs: [CDN+'3_42afcbca-5a2e-452a-b152-e7a11bfba480.webp'], desc: "قصافة أظافر كهربائية — قص آمن بدون ألم! رؤوس سيليكون ناعمة + ملف مدمج + شاحن USB.", specs: ["رؤوس سيليكون ناعمة", "ملف أظافر مدمج", "شحن USB", "آمنة للأطفال"] },
  { id: 4, name: "سيروم ذهب 24 قيراط", category: "beauty", cost: 12, price: 59, oldPrice: 89, rating: 4.9, reviews: 312, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)", icon: "💧", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'24k-goldzan-ampoule-99-9--pure-gold-serum-635-695.jpg', imgs: [CDN+'24k-goldzan-ampoule-99-9--pure-gold-serum-635-695.jpg'], desc: "سيروم ذهب عيار 99.9% — يفتح البشرة ويغذيها بعمق. أمبولات كورية أصلية.", specs: ["ذهب 99.9%", "أمبولات كورية", "30 مل", "لجميع أنواع البشرة"] },
  { id: 5, name: "فرشاة سحرية 5 في 1", category: "beauty", cost: 26, price: 99, oldPrice: null, rating: 4.6, reviews: 98, badge: null, gradient: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", icon: "🪮", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'magicbrush1.jpg', imgs: [CDN+'magicbrush1.jpg'], desc: "فرشاة سحرية متعددة الاستخدامات — تنظيف وتدليك وتصفيف. 5 رؤوس قابلة للتبديل.", specs: ["5 رؤوس", "شحن USB", "مقاومة ماء", "وزن خفيف"] },
  { id: 6, name: "سبراي إزالة الشعر 120 مل", category: "beauty", cost: 13, price: 59, oldPrice: 79, rating: 4.4, reviews: 87, badge: "خصم", gradient: "linear-gradient(135deg, #c1dfc4 0%, #deecdd 100%)", icon: "💨", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'120ml-hair-removal-spray-697-561.jpg', imgs: [CDN+'120ml-hair-removal-spray-697-561.jpg'], desc: "سبراي إزالة الشعر — رش وامسح! بدون ألم، بدون تهيج. 120 مل تكفي لعدة استخدامات.", specs: ["120 مل", "بدون ألم", "للجسم", "نتائج فورية"] },
  { id: 7, name: "قلم مكياج 4 في 1", category: "beauty", cost: 14, price: 59, oldPrice: null, rating: 4.5, reviews: 67, badge: null, gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "💄", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'4-in-1-makeup-pen-168-494.jpg', imgs: [CDN+'4-in-1-makeup-pen-168-494.jpg'], desc: "قلم مكياج متعدد — ظل عيون + أحمر شفاه + أحمر خدود + كحل. كل ما تحتاجه في قلم واحد!", specs: ["4 ألوان", "مقاوم للماء", "سهل الحمل", "هدية مثالية"] },

  // ===== Home & Kitchen =====
  { id: 8, name: "فرشاة كهربائية دوار 3 في 1", category: "home", cost: 51, price: 189, oldPrice: 249, rating: 4.7, reviews: 178, badge: "🔥 الأكثر طلباً", gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", icon: "🧹", featured: true, isNew: true, supplier: "ksadrop", img: CDN+'3-in-1-electric-spin-scrubber-machine-319-978.jpg', imgs: [CDN+'3-in-1-electric-spin-scrubber-machine-319-978.jpg'], desc: "فرشاة تنظيف كهربائية دوار 3 رؤوس — تنظف الحمام والمطبخ والأرضيات بدون مجهود. بطارية قوية.", specs: ["3 رؤوس قابلة للتبديل", "بطارية 90 دقيقة", "مقاومة ماء IPX5", "شحن USB-C"] },
  { id: 9, name: "صانعة فطائر 2 في 1", category: "home", cost: 17, price: 69, oldPrice: null, rating: 4.6, reviews: 134, badge: null, gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)", icon: "🥟", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'2-in-1-dumpling-maker-640-513.jpg', imgs: [CDN+'2-in-1-dumpling-maker-640-513.jpg'], desc: "صانعة فطائر وسامبوسا 2 في 1 — حضّر فطائر مقرمشة بثواني! تصميم عملي وسهل الاستخدام.", specs: ["2 في 1", "ستانلس ستيل", "سهلة التنظيف", "متينة"] },
  { id: 10, name: "طقم أدوات مطبخ 12 قطعة", category: "home", cost: 26, price: 99, oldPrice: 129, rating: 4.5, reviews: 56, badge: "خصم", gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "🍴", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'12-pcs-cooking-utensils-set-158-609.jpg', imgs: [CDN+'12-pcs-cooking-utensils-set-158-609.jpg'], desc: "طقم أدوات مطبخ 12 قطعة — كل ما تحتاجه في طقم واحد. سيليكون آمن للطهي ومقاوم للحرارة.", specs: ["12 قطعة", "سيليكون عالي الجودة", "مقاوم للحرارة", "آمن لجميع الأواني"] },
  { id: 11, name: "غسالة صغيرة 2 في 1", category: "home", cost: 34, price: 129, oldPrice: 169, rating: 4.7, reviews: 89, badge: "خصم", gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", icon: "🫧", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'mini_washing_machine1_1.jpg', imgs: [CDN+'mini_washing_machine1_1.jpg'], desc: "غسالة صغيرة محمولة — مثالية للملابس الداخلية وملابس الأطفال. 2 في 1: غسيل وتجفيف!", specs: ["2 في 1 غسيل وتجفيف", "محمولة", "موفرة للماء", "USB-C شحن"] },
  { id: 12, name: "كوب ترمو 40 أونصة مقبض", category: "home", cost: 56, price: 199, oldPrice: null, rating: 4.8, reviews: 45, badge: "جديد", gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)", icon: "🥤", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'40oz-tumbler-with-handle-insulated-stainless-steel-644-620.jpg', imgs: [CDN+'40oz-tumbler-with-handle-insulated-stainless-steel-644-620.jpg'], desc: "كوب ترمو 40 أونصة — ستانلس ستيل مع عزل مزدوج ومقبض. يحفظ المشروبات باردة 24 ساعة!", specs: ["40 أونصة", "ستانلس ستيل", "عزل مزدوج", "مقبض مريح"] },
  { id: 13, name: "بخاخ رش الماء 3 في 1", category: "home", cost: 22, price: 89, oldPrice: null, rating: 4.4, reviews: 67, badge: null, gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)", icon: "🌬️", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'humedifier1.jpg', imgs: [CDN+'humedifier1.jpg'], desc: "جهاز ترطيب وتهوية 3 في 1 — بخاخ ماء + مروحة + إضاءة. مثالي للمكتب والسفر.", specs: ["3 في 1", "خزان 300 مل", "إضاءة LED", "شحن USB"] },

  // ===== Mobile & Tech =====
  { id: 14, name: "شاحن لاسلكي 3 في 1", category: "tech", cost: 63, price: 229, oldPrice: 289, rating: 4.8, reviews: 267, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)", icon: "🔋", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'wirelesscharger1_09d7a2ef-ef9c-44d2-ad01-8a637d2a38f8.jpg', imgs: [CDN+'wirelesscharger1_09d7a2ef-ef9c-44d2-ad01-8a637d2a38f8.jpg'], desc: "شاحن لاسلكي 3 في 1 — يشحن الهاتف والساعة والسماعات معاً! متوافق MagSafe و Apple Watch.", specs: ["3 أجهزة معاً", "15W سريع", "MagSafe متوافق", "LED مؤشر"] },
  { id: 15, name: "سماعات Airpods Pro شاشة لمس", category: "tech", cost: 55, price: 189, oldPrice: 249, rating: 4.6, reviews: 312, badge: "خصم", gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", icon: "🎧", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'airbuds1_5.jpg', imgs: [CDN+'airbuds1_5.jpg'], desc: "سماعات Airpods Pro مع شاشة لمس — صوت ستيريو واضح، بلوتوث 5.3، إلغاء ضوضاء نشط.", specs: ["بلوتوث 5.3", "إلغاء ضوضاء", "شاشة لمس", "بطارية 6 ساعات"] },
  { id: 16, name: "ساعة ذكية A58 بلس 6 في 1", category: "tech", cost: 52, price: 179, oldPrice: 239, rating: 4.7, reviews: 198, badge: "جديد", gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)", icon: "⌚", featured: true, isNew: true, supplier: "ksadrop", img: CDN+'smart_watch1_1.webp', imgs: [CDN+'smart_watch1_1.webp'], desc: "ساعة ذكية A58 بلس — 6 ساعات互换لة! قياس ضغط + نسبة أكسجين + رياضة + تنبيهات.", specs: ["6 straps مدمجة", "قياس ضغط الدم", "SpO2 نسبة أكسجين", "مقاومة ماء IP67"] },
  { id: 17, name: "حامل تتبع هاتف 360°", category: "tech", cost: 22, price: 89, oldPrice: null, rating: 4.5, reviews: 145, badge: null, gradient: "linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)", icon: "📱", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'360_-mobile-phone-tracking-holder-167-807.jpg', imgs: [CDN+'360_-mobile-phone-tracking-holder-167-807.jpg'], desc: "حامل هاتف ذكي يدور 360° — يتتبع حركتك تلقائياً! مثالي لصناع المحتوى والاجتماعات.", specs: ["دوران 360°", "تتبع AI", "بلوتوث تحكم", "بطارية 8 ساعات"] },
  { id: 18, name: "مستقبل WiFi 4K HD", category: "tech", cost: 24, price: 99, oldPrice: null, rating: 4.3, reviews: 78, badge: null, gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "📡", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'4k-hd-wifi-receiver-303-678.jpg', imgs: [CDN+'4k-hd-wifi-receiver-303-678.jpg'], desc: "مستقبل WiFi 4K — حوّل أي شاشة عادية لتلفزيون ذكي. بث Netflix وYouTube وShahid.", specs: ["4K UHD", "WiFi مدمج", "بلوتوث 5.0", "متحكم عن بعد"] },
  { id: 19, name: "شاحن قابل للسحب 4 في 1", category: "tech", cost: 58, price: 199, oldPrice: null, rating: 4.6, reviews: 92, badge: null, gradient: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)", icon: "🔌", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'4-in-1-retractable-charger-807794.webp', imgs: [CDN+'4-in-1-retractable-charger-807794.webp'], desc: "شاحن 4 كابلات قابل للسحب — شحن 4 أجهزة بكرسي واحد! كابلات Type-C + Lightning + Micro + USB.", specs: ["4 كابلات", "قابل للسحب", "شحن سريع 65W", "حبل قابل للتمديد"] },

  // ===== Car Accessories =====
  { id: 20, name: "حامل مرآة السيارة 360°", category: "car", cost: 40, price: 149, oldPrice: 199, rating: 4.9, reviews: 534, badge: "🔥 الأكثر طلباً", gradient: "linear-gradient(135deg, #1a2a6c 0%, #b21f1f 50%, #fdbb2d 100%)", icon: "🚗", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'2_6ed17597-2485-40ef-ad29-5a66ea1b96bc.webp', imgs: [CDN+'2_6ed17597-2485-40ef-ad29-5a66ea1b96bc.webp'], desc: "حامل هاتف مرآة السيارة — تثبّت هاتفك على المرآة بدون حجب الرؤية. دوران 360°، متوافق GPS.", specs: ["تثبيت مرآة", "دوران 360°", "متوافق GPS", "تركيب فوري"] },
  { id: 21, name: "كومبرسر هواء محمول", category: "car", cost: 41, price: 149, oldPrice: 199, rating: 4.8, reviews: 167, badge: "خصم", gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)", icon: "🛞", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'air-compressor-620-729.jpg', imgs: [CDN+'air-compressor-620-729.jpg'], desc: "كومبرسر هواء محمول — انفخ الإطارات والكرات بثواني! شاشة LCD + ضغط عالي.", specs: ["150 PSI", "شاشة LCD", "شحن USB-C", "4 فوهات"] },
  { id: 22, name: "ظل نافذة سيارة 4 قطع", category: "car", cost: 51, price: 179, oldPrice: null, rating: 4.6, reviews: 98, badge: null, gradient: "linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)", icon: "🌅", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'4pcs-portable-car-side-window-shade-686-763.jpg', imgs: [CDN+'4pcs-portable-car-side-window-shade-686-763.jpg'], desc: "ظل نافذة سيارة 4 قطع — حماية من الشمس والأشعة فوق البنفسجية. تركيب فوري بدون أدوات.", specs: ["4 قطع", "حماية UV", "تركيب فوري", "قابلة للطي"] },

  // ===== Sport & Fitness =====
  { id: 23, name: "مساج 4 رؤوس", category: "sport", cost: 74, price: 249, oldPrice: 299, rating: 4.8, reviews: 312, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)", icon: "💆", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'Hcb9319cace454ceea8209869595ad723u.png', imgs: [CDN+'Hcb9319cace454ceea8209869595ad723u.png'], desc: "مساج كهربائي 4 رؤوس — حرارة تدفئة + تدليك عميق. خفّف آلام الرقبة والكتف بعد يوم طويل.", specs: ["4 رؤوس تدليك", "حرارة تدفئة", "بطارية 1200 mAh", "قابل للطي"] },
  { id: 24, name: "بكر بطن 2 في 1", category: "sport", cost: 49, price: 169, oldPrice: null, rating: 4.5, reviews: 134, badge: null, gradient: "linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)", icon: "💪", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'support_auto1_1.jpg', imgs: [CDN+'support_auto1_1.jpg'], desc: "بكر بطن 2 في 1 مع دعم تلقائي — يقوي العضلات ويحسن القوام. مثالي للتمارين المنزلية.", specs: ["2 في 1", "دعم تلقائي", "رغام مطاطي", "مقاوم للانزلاق"] },
  { id: 25, name: "طريق مقوي الظهر", category: "sport", cost: 29, price: 109, oldPrice: 139, rating: 4.7, reviews: 89, badge: "خصم", gradient: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)", icon: "🧍", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'download_6_9234e15b-89d3-4efd-a172-d34829c534c6.jpg', imgs: [CDN+'download_6_9234e15b-89d3-4efd-a172-d34829c534c6.jpg'], desc: "حزام تقوية الظهر — يصحح القوام ويخفف آلام الظهر. مثالي للمكتبين والسائقين.", specs: ["تصحيح القوام", "مريح للارتداء", "قابل للتعديل", "مخفي تحت الملابس"] },
  { id: 26, name: "طريق قبضة اليد 6 قطع", category: "sport", cost: 36, price: 129, oldPrice: null, rating: 4.4, reviews: 67, badge: null, gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", icon: "🤲", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'gripper1.jpg', imgs: [CDN+'gripper1.jpg'], desc: "طريق قبضة اليد 6 قطع — يقوي عضلات اليد والساعد. مثالي للرياضيين ومستخدمي الكمبيوتر.", specs: ["6 قطع مقاومات مختلفة", "سيليكون مريح", "سهلة الحمل", "للرجال والنساء"] },

  // ===== Fashion =====
  { id: 27, name: "ساعة كاسيو ديجيتال رجالية", category: "fashion", cost: 65, price: 229, oldPrice: 299, rating: 4.8, reviews: 456, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #1a2a6c 0%, #b21f1f 50%, #fdbb2d 100%)", icon: "⌚", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'smart_watch1_1.webp', imgs: [CDN+'smart_watch1_1.webp'], desc: "ساعة كاسيو ديجيتال أصلية — مقاومة للماء، منبه متعدد، إضاءة ليلية. تصميم كلاسيكي.", specs: ["Casio أصلية", "مقاومة ماء 50م", "منبه متعدد", "إضاءة ليلية"] },
  { id: 28, name: "بخور المسك العماني", category: "fashion", cost: 27, price: 89, oldPrice: null, rating: 4.6, reviews: 178, badge: "أصلي", gradient: "linear-gradient(135deg, #834d9b 0%, #d04ed6 100%)", icon: "🪔", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'1_9c8fd918-d54f-48b4-80b4-ba30cafd5a65.webp', imgs: [CDN+'1_9c8fd918-d54f-48b4-80b4-ba30cafd5a65.webp'], desc: "بخور المسك العماني الأصلي — 40 غرام. عطر فاخر يملأ المكان برائحة مميزة تدوم طويلاً.", specs: ["40 غرام", "أصلي عماني", "رائحة تدوم", "عبوة فاخرة"] },
  { id: 29, name: "ساعة ذكية A58 بلس مع 6 ساعات互换لة", category: "fashion", cost: 52, price: 179, oldPrice: 229, rating: 4.7, reviews: 67, badge: "خصم", gradient: "linear-gradient(135deg, #f5af19 0%, #f12711 100%)", icon: "⌚", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'smart_watch1_1.webp', imgs: [CDN+'smart_watch1_1.webp'], desc: "ساعة ذكية A58 بلس — تأتي مع 6 ساعات互换لة! قياس ضغط الدم والأكسجين والرياضة.", specs: ["6 ساعات互换لة", "قياس صحي", "مقاومة ماء IP67", "شحن مغناطيسي"] },

  // ===== Kids & Babies =====
  { id: 30, name: "طائرة تحكم عن بعد", category: "kids", cost: 98, price: 329, oldPrice: 399, rating: 4.9, reviews: 45, badge: "🔥 رائج", gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)", icon: "✈️", featured: true, isNew: true, supplier: "ksadrop", img: CDN+'3_4f2c2a49-9c9c-49b4-b903-e4f1086b64c5.webp', imgs: [CDN+'3_4f2c2a49-9c9c-49b4-b903-e4f1086b64c5.webp'], desc: "طائرة تحكم عن بعد — تطير بسهولة وثبات! مثالية للأطفال من 8 سنوات. جهاز تحكم سهل.", specs: ["تحكم عن بعد", "طيران ثابت", "بطارية 15 دقيقة", "مناسب من 8 سنوات"] },

  // ===== Additional Products with Real Images =====
  { id: 31, name: "ريسيفر شاشة ساعة 3D لاسلكي", category: "tech", cost: 45, price: 159, oldPrice: null, rating: 4.6, reviews: 56, badge: null, gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "🕐", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'3_4f2c2a49-9c9c-49b4-b903-e4f1086b64c5.webp', imgs: [CDN+'3_4f2c2a49-9c9c-49b4-b903-e4f1086b64c5.webp'], desc: "ساعة LED رقمية 3D لاسلكية — تحكم عن بعد، شاشة كبيرة، تصميم عصري.", specs: ["شاشة LED 3D", "تحكم عن بعد", "شحن USB", "منبه مزدوج"] },
  { id: 32, name: "مجفف شعر Joy 2 في 1 احترافي", category: "beauty", cost: 69, price: 239, oldPrice: 299, rating: 4.8, reviews: 156, badge: "خصم", gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", icon: "💇‍♀️", featured: true, isNew: false, supplier: "ksadrop", img: CDN+'WhatsAppImage1446-12-18at15.13.09_2.jpg', imgs: [CDN+'WhatsAppImage1446-12-18at15.13.09_2.jpg'], desc: "مجفف شعر Joy 2 في 1 — احترافي وقوي. تقنية أيون سلبية لحماية الشعر من التلف.", specs: ["2200 واط", "تقنية أيون سلبية", "3 درجات حرارة", "2 فوهات"] },
  { id: 33, name: "سماعات ABS Airpods Pro 2", category: "tech", cost: 26, price: 99, oldPrice: 139, rating: 4.5, reviews: 234, badge: "خصم", gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", icon: "🎧", featured: false, isNew: false, supplier: "ksadrop", img: CDN+'WhatsApp-Image-2025-01-19-at-7.27.06-PM_68a2d1690f01b.jpg', imgs: [CDN+'WhatsApp-Image-2025-01-19-at-7.27.06-PM_68a2d1690f01b.jpg'], desc: "سماعات Airpods Pro 2 — صوت واضح مع إلغاء الضوضاء. شاشة عرض مدمجة في العلبة.", specs: ["إلغاء ضوضاء نشط", "شاشة عرض", "بلوتوث 5.3", "بطارية 5 ساعات"] },
  { id: 34, name: "جهاز غسيل الفم 3 في 1", category: "beauty", cost: 38, price: 139, oldPrice: null, rating: 4.7, reviews: 89, badge: null, gradient: "linear-gradient(135deg, #c1dfc4 0%, #deecdd 100%)", icon: "🦷", featured: false, isNew: true, supplier: "ksadrop", img: CDN+'oralirrigator_5.jpg', imgs: [CDN+'oralirrigator_5.jpg'], desc: "جهاز غسيل الفم 3 في 1 — تنظيف عميق بين الأسنان. 3 أوضاع ضغط، خزان 300 مل.", specs: ["3 أوضاع", "خزان 300 مل", "شحن USB-C", "رؤوس قابلة للتبديل"] },
  { id: 35, name: "بخور ذهبي 24 قيراط للمنزل", category: "home", cost: 27, price: 99, oldPrice: null, rating: 4.8, reviews: 312, badge: "ترند", gradient: "linear-gradient(135deg, #d4af37 0%, #1a1a2e 100%)", icon: "🪔", featured: true, isNew: true, supplier: "ksadrop", img: CDN+'1_9c8fd918-d54f-48b4-80b4-ba30cafd5a65.webp', imgs: [CDN+'1_9c8fd918-d54f-48b4-80b4-ba30cafd5a65.webp'], desc: "بخور العود العماني الفاخر — رائحة ذهبية تدوم ساعات. مثالي للمنزل والمجالس.", specs: ["40 غرام", "أصلي عماني", "رائحة ذهبية", "عبوة هدايا"] }
];

const CATEGORY_NAMES = {
  beauty: "العناية والجمال",
  home: "المنزل والمطبخ",
  tech: "إلكترونيات وتقنية",
  car: "إكسسوارات السيارة",
  sport: "رياضة ولياقة",
  fashion: "أزياء وإكسسوارات",
  kids: "أطفال ولعب"
};

const SUPPLIER_INFO = {
  ksadrop: { name: "KSA Drop", url: "https://ksadrop.com", shipping: "2-5 أيام عمل", cod: true },
  m5azn: { name: "M5AZN", url: "https://m5azn.com", shipping: "3-7 أيام عمل", cod: true }
};