// ===== Product Data — Dropshipping from KSA Drop + M5AZN =====
// Prices: Wholesale cost (what we pay) → Retail price (what customer pays)
// Margin formula: retail = cost × 2.5 to 3.5 (industry standard for dropshipping)
// Currency: SAR (Saudi Riyal)

const PRODUCTS = [
  // ===== Health & Beauty =====
  { id: 1, name: "مبخرة إلكترونية محمولة", category: "beauty", cost: 21, price: 89, oldPrice: 129, rating: 4.8, reviews: 234, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", icon: "🪔", featured: true, isNew: false, supplier: "ksadrop", desc: "مبخرة إلكترونية أنيقة ومحمولة — أشعل البخور بضغطة زر. مثالية للمنزل والمكتب والسيارة. بطارية قابلة للشحن تدوم طويلاً.", specs: ["شحن USB-C", "بطارية 1200 mAh", "تشغيل بضغطة واحدة", "تصميم محمول"], margin: 323 },
  { id: 2, name: "مسدس إزالة الشعر الدائم", category: "beauty", cost: 48, price: 179, oldPrice: 229, rating: 4.7, reviews: 189, badge: "خصم", gradient: "linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)", icon: "✨", featured: true, isNew: false, supplier: "ksadrop", desc: "تقنية IPL متقدمة لإزالة الشعر بشكل دائم — آمنة وفعالة للمناطق الحساسة. نتائج ملموسة خلال 4 أسابيع.", specs: ["تقنية IPL", "500,000 نبضة", "5 مستويات طاقة", "نتائج خلال 4 أسابيع"], margin: 273 },
  { id: 3, name: "جهاز قياس ضغط الدم الرقمي", category: "beauty", cost: 18, price: 79, oldPrice: null, rating: 4.5, reviews: 145, badge: null, gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)", icon: "🩺", featured: false, isNew: true, supplier: "ksadrop", desc: "جهاز قياس ضغط الدم الرقمي — شاشة LCD كبيرة، دقة عالية، ذاكرة 120 قراءة. مثالي للمتابعة اليومية.", specs: ["شاشة LCD كبيرة", "ذاكرة 120 قراءة", "دقة ±3 mmHg", "بطارية AAA"], margin: 339 },
  { id: 4, name: "سيروم فيتامين C الأصلي", category: "beauty", cost: 29, price: 119, oldPrice: 149, rating: 4.9, reviews: 312, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)", icon: "💧", featured: true, isNew: false, supplier: "ksadrop", desc: "سيروم فيتامين C المركز 20% — يفتح البشرة ويقلل التصبغات والخطوط الدقيقة. مركب The Ordinary الأصلي.", specs: ["فيتامين C 20%", "هيالورونيك أسيد", "30 مل", "أصلي 100%"], margin: 310 },
  { id: 5, name: "كريم إزالة الحبوب الأصلي", category: "beauty", cost: 31, price: 129, oldPrice: null, rating: 4.6, reviews: 98, badge: null, gradient: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", icon: "🧴", featured: false, isNew: true, supplier: "ksadrop", desc: "كريم علاج الحبوب والبثور — تركيبة The Ordinary Blemish Control الأصلية. يقلل الالتهاب ويمنع ظهور حبوب جديدة.", specs: ["نياسيناميد + زنك", "30 مل", "أصلي 100%", "للبشرة الدهنية"], margin: 316 },
  { id: 6, name: "مشط فرد الشعر المحمول", category: "beauty", cost: 13, price: 59, oldPrice: 79, rating: 4.4, reviews: 87, badge: "خصم", gradient: "linear-gradient(135deg, #c1dfc4 0%, #deecdd 100%)", icon: "💇", featured: false, isNew: false, supplier: "ksadrop", desc: "مشط فرد الشعر الكهربائي المحمول — يفرد الشعر بسرعة وبدون أذى. خفيف ومثالي للسفر.", specs: ["شحن USB", "3 درجات حرارة", "سيراميك مضاد للكهرباء", "وزن خفيف"], margin: 354 },

  // ===== Home & Kitchen =====
  { id: 7, name: "صينية تدفئة الطعام الكهربائية", category: "home", cost: 45, price: 189, oldPrice: 249, rating: 4.9, reviews: 456, badge: "🔥 الأكثر طلباً", gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)", icon: "🍽️", featured: true, isNew: false, supplier: "ksadrop", desc: "صينية تدفئة كهربائية — حافظ على طعامك دافئ طوال وجبة العشاء! مثالية للعائلات الكبيرة ومائدة رمضان. مطاط سيليكون قابل للطي.", specs: ["سيليكون قابل للطي", "3 درجات حرارة", "مقاومة للماء IPX4", "شاشة LED"], margin: 320 },
  { id: 8, name: "فرشاة كهربائية دوار 3 في 1", category: "home", cost: 51, price: 219, oldPrice: 279, rating: 4.7, reviews: 178, badge: "جديد", gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", icon: "🧹", featured: true, isNew: true, supplier: "ksadrop", desc: "فرشاة تنظيف كهربائية دوار 3 رؤوس — تنظف الحمام والمطبخ والأرضيات بدون مجهود. بطارية قوية تدوم 90 دقيقة.", specs: ["3 رؤوس قابلة للتبديل", "بطارية 90 دقيقة", "مقاومة ماء IPX5", "شحن USB-C"], margin: 329 },
  { id: 9, name: "قاطعة خضار 3 في 1 ستانلس ستيل", category: "home", cost: 31, price: 129, oldPrice: null, rating: 4.6, reviews: 134, badge: null, gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)", icon: "🔪", featured: false, isNew: true, supplier: "ksadrop", desc: "قاطعة خضار متعددة الوظائف — تقطع شرائح ومكعبات وجوليات بثواني. ستانلس ستيل مقاوم للصدأ.", specs: ["ستانلس ستيل 304", "3 شفرات", "حاوية جمع", "آمنة لغسالة الصحون"], margin: 316 },
  { id: 10, name: "كيس تفريغ هواء محمول", category: "home", cost: 59, price: 249, oldPrice: 299, rating: 4.8, reviews: 89, badge: "خصم", gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", icon: "💨", featured: true, isNew: false, supplier: "ksadrop", desc: "كيس تفريغ الهواء المضغوط — وفّر 80% من مساحة التخزين! مثالي للملابس الباردة والبطانيات والوسائد.", specs: ["ضغط 150 PSI", "شحن USB-C", "5 أكياس مجانية", "مانع تسرب"], margin: 322 },
  { id: 11, name: "صانعة ساندويش الإفطار", category: "home", cost: 24, price: 99, oldPrice: null, rating: 4.5, reviews: 67, badge: null, gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)", icon: "🥪", featured: false, isNew: false, supplier: "ksadrop", desc: "صانعة ساندويش إفطار كهربائية — حضّر ساندويشات مقرمشة بثواني. سطح مزدوج مانع للالتصاق.", specs: ["سطح مزدوج", "مانع الالتصاق", "مؤشر LED", "سهلة التنظيف"], margin: 313 },
  { id: 12, name: "حامل منظم للمطبخ", category: "home", cost: 24, price: 99, oldPrice: 129, rating: 4.4, reviews: 56, badge: null, gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "🗄️", featured: false, isNew: false, supplier: "ksadrop", desc: "منظم مطبخ متعدد الطبقات — رتّب التوابل والأواني بمكان واحد. توفير مساحة وترتيب مثالي.", specs: ["3 طبقات", "ستانلس ستيل", "قابل للفك", "مقاوم للصدأ"], margin: 313 },

  // ===== Mobile & Tech =====
  { id: 13, name: "شاحن مغناطيسي لاسلكي قابل للطي", category: "tech", cost: 29, price: 129, oldPrice: 169, rating: 4.8, reviews: 267, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)", icon: "🔋", featured: true, isNew: false, supplier: "ksadrop", desc: "شاحن مغناطيسي لاسلكي 15W — قابل للطي ومتوافق MagSafe. شحن سريع لجميع أجهزة iPhone وAirPods.", specs: ["15W سريع", "MagSafe متوافق", "قابل للطي", "LED مؤشر"], margin: 345 },
  { id: 14, name: "سماعات M10 برو", category: "tech", cost: 22, price: 89, oldPrice: 129, rating: 4.6, reviews: 312, badge: "خصم", gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", icon: "🎧", featured: true, isNew: false, supplier: "ksadrop", desc: "سماعات أذن لاسلكية M10 — صوت ستيريو واضح، بلوتوث 5.3، بطارية تدوم 6 ساعات. مثالية للرياضة والعمل.", specs: ["بلوتوث 5.3", "بطارية 6 ساعات", "مقاومة ماء IPX5", "شحن USB-C"], margin: 305 },
  { id: 15, name: "بنك طاقة 20000 mAh سريع", category: "tech", cost: 45, price: 189, oldPrice: 239, rating: 4.7, reviews: 198, badge: "جديد", gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)", icon: "⚡", featured: true, isNew: true, supplier: "ksadrop", desc: "بنك طاقة 20000 mAh بشحن سريع 65W — يشحن اللابتوب والهاتف معاً! كابل مدمج + شاشة LED رقمية.", specs: ["20000 mAh", "65W PD سريع", "كابل مدمج", "شاشة LED"], margin: 320 },
  { id: 16, name: "حامل تتبع هاتف 360°", category: "tech", cost: 22, price: 99, oldPrice: null, rating: 4.5, reviews: 145, badge: null, gradient: "linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)", icon: "📱", featured: false, isNew: true, supplier: "ksadrop", desc: "حامل هاتف ذكي يدور 360° — يتتبع حركتك تلقائياً! مثالي لصناع المحتوى والاجتماعات المرئية.", specs: ["دوران 360°", "تتبع AI", "بلوتوث تحكم", "بطارية 8 ساعات"], margin: 350 },
  { id: 17, name: "مستقبل WiFi 4K HD", category: "tech", cost: 24, price: 99, oldPrice: null, rating: 4.3, reviews: 78, badge: null, gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "📡", featured: false, isNew: false, supplier: "ksadrop", desc: "مستقبل WiFi 4K — حوّل أي شاشة عادية لتلفزيون ذكي. بث Netflix وYouTube وShahid مباشرة.", specs: ["4K UHD", "WiFi 6", "بلوتوث 5.0", "متحكم عن بعد"], margin: 313 },
  { id: 18, name: "نظارة بلوتوث ذكية", category: "tech", cost: 17, price: 79, oldPrice: 119, rating: 4.4, reviews: 92, badge: "خصم", gradient: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)", icon: "🥽", featured: false, isNew: false, supplier: "ksadrop", desc: "نظارة شمسية بلوتوث ذكية — استمع للموسيقى وأجعل المكالمات بيد حرة! صوت مفتوح بدون سماعات ظاهرة.", specs: ["بلوتوث 5.0", "مكبر صوت مدمج", "UV400 حماية", "بطارية 6 ساعات"], margin: 365 },

  // ===== Car Accessories =====
  { id: 19, name: "منظم فجوة المقعد الجلدي", category: "car", cost: 20, price: 89, oldPrice: 129, rating: 4.9, reviews: 534, badge: "🔥 الأكثر طلباً", gradient: "linear-gradient(135deg, #1a2a6c 0%, #b21f1f 50%, #fdbb2d 100%)", icon: "🚗", featured: true, isNew: false, supplier: "ksadrop", desc: "منظم فجوة المقعد الجلدي — تخلص من مشكلة سقوط الهاتف والمفاتيح بين المقاعد! جلد فاخر + حامل أكواب مدمج.", specs: ["جلد PU فاخر", "حامل أكواب", "تركيب بدون أدوات", "متوافق جميع السيارات"], margin: 345 },
  { id: 20, name: "حامل هاتف مغناطيسي للسيارة", category: "car", cost: 15, price: 69, oldPrice: null, rating: 4.7, reviews: 289, badge: null, gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", icon: "📱", featured: false, isNew: false, supplier: "ksadrop", desc: "حامل هاتف مغناطيسي قوي — تثبّت هاتفك بثبات على أقوى المطبات. مغناطيس N52 فائق القوة.", specs: ["مغناطيس N52", "دوران 360°", "تركيب فوري", "متوافق MagSafe"], margin: 360 },
  { id: 21, name: "كومبرسر هواء محمول", category: "car", cost: 59, price: 249, oldPrice: 299, rating: 4.8, reviews: 167, badge: "خصم", gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)", icon: "🛞", featured: true, isNew: false, supplier: "ksadrop", desc: "كومبرسر هواء محمول — انفخ الإطارات والكرات والأ mattresses بثواني! شاشة LCD + ضغط 150 PSI.", specs: ["150 PSI", "شاشة LCD", "شحن USB-C", "4 فوهات"], margin: 322 },
  { id: 22, name: "قفازات شتوية تدفئة ذاتية", category: "car", cost: 35, price: 149, oldPrice: 199, rating: 4.6, reviews: 98, badge: "🔥 جديد", gradient: "linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)", icon: "🧤", featured: true, isNew: true, supplier: "ksadrop", desc: "قفازات شتوية بتدفئة ذاتية — مثالية لسائقي الدراجات والتوصيل. 3 مستويات حرارة تدفئ أصابعك في أبرد الأيام.", specs: ["3 مستويات حرارة", "بطارية 8 ساعات", "شحن USB", "مقاومة رياح"], margin: 326 },

  // ===== Sport & Fitness =====
  { id: 23, name: "حزام تنحيف البطن الذكي", category: "sport", cost: 33, price: 139, oldPrice: 179, rating: 4.5, reviews: 234, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)", icon: "💪", featured: true, isNew: false, supplier: "ksadrop", desc: "حزام تنحيف البطن بتقنية EMS — يحفّز العضلات أثناء الراحة! 6 أوضاع و10 مستويات شدة.", specs: ["تقنية EMS", "6 أوضاع", "10 مستويات", "شحن USB-C"], margin: 321 },
  { id: 24, name: "مساج الرقبة والكتف", category: "sport", cost: 35, price: 149, oldPrice: null, rating: 4.8, reviews: 312, badge: null, gradient: "linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)", icon: "💆", featured: false, isNew: false, supplier: "ksadrop", desc: "مساج كهربائي للرقبة والكتف — حرارة تدفئة + تدليك عميق. خفّف آلام العنق بعد يوم طويل.", specs: ["حرارة تدفئة", "6 رؤوس تدليك", "بطارية 1200 mAh", "قابل للطي"], margin: 326 },
  { id: 25, name: "بساط مساج القدم الكامل", category: "sport", cost: 106, price: 449, oldPrice: 549, rating: 4.7, reviews: 89, badge: "خصم", gradient: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)", icon: "🦶", featured: false, isNew: false, supplier: "ksadrop", desc: "بساط مساج كهربائي للقدم — حرارة + تدليك ضغط + اهتزاز. يخفف التعب والإرهاق بعد الوقوف الطويل.", specs: ["حرارة تدفئة", "ضغط هوائي", "15 وضع", "جهاز تحكم عن بعد"], margin: 323 },
  { id: 26, name: "مروحة تبريد محمولة مini", category: "sport", cost: 27, price: 109, oldPrice: null, rating: 4.3, reviews: 67, badge: null, gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)", icon: "🌬️", featured: false, isNew: true, supplier: "ksadrop", desc: "مروحة تبريد محمولة صغيرة — رطّب وبرّد الهواء في مكانك! مثالية للمكتب والسفر والخيام.", specs: ["خزان 300 مل", "3 سرعات", "شحن USB-C", "وزن 350 غرام"], margin: 304 },

  // ===== Fashion =====
  { id: 27, name: "ساعة كاسيو ديجيتال رجالية", category: "fashion", cost: 65, price: 249, oldPrice: 329, rating: 4.8, reviews: 456, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #1a2a6c 0%, #b21f1f 50%, #fdbb2d 100%)", icon: "⌚", featured: true, isNew: false, supplier: "ksadrop", desc: "ساعة Casio ديجيتال أصلية — مقاومة للماء، منبه متعدد، إضاءة ليلية. تصميم كلاسيكي لا يخرج عن الموضة.", specs: ["Casio أصلية", "مقاومة ماء 50م", "منبه متعدد", "إضاءة ليلية"], margin: 283 },
  { id: 28, name: "محفظة جلد RFID حماية", category: "fashion", cost: 20, price: 89, oldPrice: null, rating: 4.6, reviews: 178, badge: null, gradient: "linear-gradient(135deg, #834d9b 0%, #d04ed6 100%)", icon: "👛", featured: false, isNew: false, supplier: "ksadrop", desc: "محفظة جلد طبيعي بحماية RFID — 12 خانة بطاقة + جيب عملات + حامل ID. أنيقة وآمنة.", specs: ["جلد طبيعي", "RFID حماية", "12 خانة بطاقة", "صندوق هدايا"], margin: 345 },
  { id: 29, name: "حقيبة أطفال ظهر أنيقة", category: "fashion", cost: 101, price: 399, oldPrice: 499, rating: 4.7, reviews: 67, badge: "خصم", gradient: "linear-gradient(135deg, #f5af19 0%, #f12711 100%)", icon: "🎒", featured: false, isNew: false, supplier: "ksadrop", desc: "حقيبة أطفال فاخرة — مقاومة للماء، عزل حراري للرضاعات، حامل أطفال مدمج. كل ما تحتاجه الأم في حقيبة واحدة!", specs: ["عزل حراري", "مقاومة ماء", "حامل أطفال", "USB شحن"], margin: 295 },
  { id: 30, name: "كرسي أطفال قابل للطي", category: "fashion", cost: 243, price: 799, oldPrice: 999, rating: 4.9, reviews: 45, badge: "فاخر", gradient: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)", icon: "🪑", featured: false, isNew: false, supplier: "ksadrop", desc: "كرسي أطفال عالي قابل للطي — آمن ومريح، صينية طعام قابلة للإزالة، حزام أمان 5 نقاط.", specs: ["حزام 5 نقاط", "قابل للطي", "صينية قابلة للإزالة", "حتى 15 كجم"], margin: 229 },

  // ===== Toys & Babies =====
  { id: 31, name: "قصافة أظافر أطفال كهربائية", category: "kids", cost: 15, price: 69, oldPrice: 89, rating: 4.8, reviews: 234, badge: "🔥 رائج", gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)", icon: "✂️", featured: true, isNew: true, supplier: "ksadrop", desc: "قصافة أظافر أطفال كهربائية — قص آمن بدون ألم! رؤوس سيليكون ناعمة + إضاءة LED + جهاز تفريغ.", specs: ["رؤوس سيليكون", "إضاءة LED", "بطارية مدمجة", "آمنة من الولادة"], margin: 360 },
  { id: 32, name: "مبخرة سحابة مطر", category: "kids", cost: 38, price: 159, oldPrice: null, rating: 4.5, reviews: 89, badge: null, gradient: "linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)", icon: "☁️", featured: false, isNew: true, supplier: "ksadrop", desc: "مبخرة سحابة مطر — إضاءة ألوان + رذاذ بارد + صوت مطر! تجربة مريحة وممتعة للأطفال والكبار.", specs: ["7 ألوان LED", "رذاذ بارد", "خزان 300 مل", "شحن USB"], margin: 318 },
  { id: 33, name: "صندوق مجوهرات شاشة طي", category: "kids", cost: 14, price: 59, oldPrice: null, rating: 4.4, reviews: 56, badge: null, gradient: "linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)", icon: "💍", featured: false, isNew: false, supplier: "ksadrop", desc: "صندوق مجوهرات بشاشة طي مبتكرة — مرآة + إضاءة + منظم حلقات وأقراط. هدية مثالية!", specs: ["شاشة طي", "مرآة + إضاءة", "منظم حلقات", "صندوق هدايا"], margin: 321 },

  // ===== Skincare (High Margin) =====
  { id: 34, name: "سيروم هيالورونيك أسيد الأصلي", category: "beauty", cost: 29, price: 119, oldPrice: 159, rating: 4.8, reviews: 267, badge: "الأكثر مبيعاً", gradient: "linear-gradient(135deg, #c1dfc4 0%, #deecdd 100%)", icon: "✨", featured: true, isNew: false, supplier: "m5azn", desc: "سيروم الهيالورونيك أسيد — ترطيب عميق 72 ساعة. يملأ الخطوط الدقيقة ويعطي البشرة إشراقة طبيعية.", specs: ["هيالورونيك 2%", "فيتامين B5", "30 مل", "أصلي The Ordinary"], margin: 310 },
  { id: 35, name: "بالمرموفر ميك أب الأصلي", category: "beauty", cost: 29, price: 119, oldPrice: null, rating: 4.7, reviews: 156, badge: null, gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)", icon: "🧴", featured: false, isNew: false, supplier: "m5azn", desc: "بالمرموفر ميك أب أصلي — يذيب المكياج العنيد بلطف. تركيبة زيتية تغذي البشرة ولا تجففها.", specs: ["تركيبة زيتية", "120 مل", "أصلي 100%", "لجميع أنواع البشرة"], margin: 310 },
  { id: 36, name: "قناع ترطيب الوجه بالبخار", category: "beauty", cost: 47, price: 189, oldPrice: 239, rating: 4.6, reviews: 78, badge: "خصم", gradient: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)", icon: "🧖", featured: false, isNew: true, supplier: "ksadrop", desc: "جهاز بخار الوجه — يفتح المسام ويرطب البشرة بعمق. 3 مستويات بخار + أوضاع SPA مريحة.", specs: ["3 مستويات بخار", "خزان 70 مل", "أوضاع SPA", "شحن USB"], margin: 302 },

  // ===== Trending Winners =====
  { id: 37, name: "مكواة محمولة الجيل الجديد", category: "home", cost: 25, price: 109, oldPrice: 149, rating: 4.7, reviews: 189, badge: "🔥 ترند", gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)", icon: "👔", featured: true, isNew: true, supplier: "ksadrop", desc: "مكواة بخار محمولة الجيل الجديد — مكوي عمودي بدون طاولة! سيراميك 150°C، خفيفة 700 غرام.", specs: ["سيراميك 150°C", "700 غرام فقط", "بخار عمودي", "شحن USB-C"], margin: 336 },
  { id: 38, name: "زابل مائي فائق الامتصاص", category: "home", cost: 16, price: 69, oldPrice: null, rating: 4.4, reviews: 45, badge: null, gradient: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)", icon: "🧽", featured: false, isNew: false, supplier: "ksadrop", desc: "زابل مائي فائق الامتصاص — يجف خلال ثواني! مثالي للحمام والمطبخ والمدخل.", specs: ["امتصاص فائق", "يجف بثواني", "غسالة غسيل", "أحجام متعددة"], margin: 331 },
  { id: 39, name: "شامبو تقوية النعناع", category: "beauty", cost: 14, price: 59, oldPrice: null, rating: 4.5, reviews: 67, badge: null, gradient: "linear-gradient(135deg, #c1dfc4 0%, #deecdd 100%)", icon: "🌿", featured: false, isNew: false, supplier: "ksadrop", desc: "شامبو بالنعناع الطبيعي — يقوي الشعر من الجذور ويمنع التساقط. منعش ومهدئ لفروة الرأس.", specs: ["نعناع طبيعي", "100 مل", "بدون سلفات", "لجميع أنواع الشعر"], margin: 321 },
  { id: 40, name: "مكواة فرد الشعر اللاسلكية", category: "beauty", cost: 36, price: 149, oldPrice: 199, rating: 4.7, reviews: 145, badge: "خصم", gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)", icon: "💇‍♀️", featured: true, isNew: false, supplier: "ksadrop", desc: "مكواة فرد الشعر اللاسلكية — حرارة سيراميك 200°C، بطارية تدوم 40 دقيقة. مثالية للسفر والعمل.", specs: ["سيراميك 200°C", "بطارية 40 دقيقة", "شحن USB-C", "وزن 250 غرام"], margin: 314 }
];

const CATEGORY_NAMES = {
  beauty: "العناية والجمال",
  home: "المنزل والمطبخ",
  tech: "إلكترونيات و تقنية",
  car: "إكسسوارات السيارة",
  sport: "رياضة ولياقة",
  fashion: "أزياء وإكسسوارات",
  kids: "أطفال ولعب"
};

const SUPPLIER_INFO = {
  ksadrop: { name: "KSA Drop", url: "https://ksadrop.com", shipping: "2-5 أيام", cod: true },
  m5azn: { name: "M5AZN", url: "https://m5azn.com", shipping: "3-7 أيام", cod: true }
};